/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleAtirador;
import controleatleta.Endereco;
import controleatleta.Premiacao;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.Atirador;
import model.Prova;
import model.Sequencia;

/**
 *
 * @author Andre
 */
public class CadastroAtirador extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAtirador
     */
    private DefaultListModel jModelAtiradores;
    private DefaultListModel jModelProvas;
    private DefaultListModel jModelPremiacao;
    private DefaultListModel jModelSequencias;
    private DefaultListModel jModelTelefones;
    private DefaultListModel jModelDefault;
    private DateFormat dateFormat;
    private ComboBoxModel emptyModel;
    private int saveMode;
    private ControleAtirador controle;
    private Atirador atiradorSelecionado;

    public CadastroAtirador() {
        initComponents();
        initMoreComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainelTab1 = new javax.swing.JTabbedPane();
        jPainel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAtiradores = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jTextoNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextoDataNasc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextoAltura = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextoTelefone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonAddTelefone = new javax.swing.JButton();
        jTextoCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextoRg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextoNomePai = new javax.swing.JTextField();
        jTextoNomeMae = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextoPeso = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonRemoveTelefone = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTelefones = new javax.swing.JList();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBoxClasse = new javax.swing.JComboBox();
        jComboBoxPosicao = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jTextoLogradouro = new javax.swing.JTextField();
        jTextoNumero = new javax.swing.JTextField();
        jTextoBairro = new javax.swing.JTextField();
        jTextoCidade = new javax.swing.JTextField();
        jTextoEstado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextoPais = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextoComplemento = new javax.swing.JTextField();
        jTextoCep = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTextoDistancia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextoArma = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextoModo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListProvas = new javax.swing.JList();
        jButtonRemoveProva = new javax.swing.JButton();
        jButtonAddProva = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextoTitulo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextoAno = new javax.swing.JTextField();
        jButtonRemovePremiacao = new javax.swing.JButton();
        jButtonAddPremiacao = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListPremiacao = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTextoEvento = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextoPontos = new javax.swing.JTextField();
        jComboBoxProva = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListSequencias = new javax.swing.JList();
        jButtonAddSequencia = new javax.swing.JButton();
        jButtonRemoveSequencia = new javax.swing.JButton();
        jComboBoxSexo = new javax.swing.JComboBox();
        jButtonAdicionar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jComboBoxPesquisa = new javax.swing.JComboBox();
        jTextoPesquisa = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListAtiradores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListAtiradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAtiradoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListAtiradores);

        jLabel1.setText("Nome");

        jLabel2.setText("Data Nasc.");

        jLabel5.setText("Sexo");

        jLabel6.setText("Altura");

        jLabel3.setText("Telefone");

        jButtonAddTelefone.setText("+");
        jButtonAddTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTelefoneActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF");

        jLabel7.setText("RG");

        jLabel9.setText("Nome Pai");

        jLabel10.setText("Nome Mãe");

        jLabel11.setText("Peso");

        jButtonRemoveTelefone.setText("-");
        jButtonRemoveTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveTelefoneActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jListTelefones);

        jLabel27.setText("Posição");

        jLabel28.setText("Classe");

        jComboBoxClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Portador" }));

        jComboBoxPosicao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Destro", "Canhoto" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextoNomePai, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jTextoNomeMae, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jComboBoxClasse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxPosicao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextoRg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextoCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(132, 132, 132)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextoTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAddTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonRemoveTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextoNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextoNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jComboBoxPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButtonRemoveTelefone)
                            .addComponent(jButtonAddTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jComboBoxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel1);

        jLabel12.setText("Cidade");

        jLabel13.setText("Estado");

        jLabel14.setText("Bairro");

        jLabel8.setText("Numero");

        jLabel15.setText("Logradouro");

        jLabel16.setText("Pais");

        jLabel17.setText("Complemento");

        jLabel18.setText("CEP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Endereço", jPanel2);

        jLabel19.setText("Distancia");

        jLabel20.setText("Arma");

        jLabel21.setText("Modo");

        jScrollPane3.setViewportView(jListProvas);

        jButtonRemoveProva.setText("-");
        jButtonRemoveProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveProvaActionPerformed(evt);
            }
        });

        jButtonAddProva.setText("+");
        jButtonAddProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddProvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextoArma, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jTextoDistancia)
                    .addComponent(jTextoModo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRemoveProva, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jButtonAddProva, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButtonAddProva)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveProva))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextoDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextoArma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextoModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Provas", jPanel3);

        jLabel22.setText("Titulo");

        jLabel23.setText("Ano");

        jButtonRemovePremiacao.setText("-");
        jButtonRemovePremiacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePremiacaoActionPerformed(evt);
            }
        });

        jButtonAddPremiacao.setText("+");
        jButtonAddPremiacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPremiacaoActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jListPremiacao);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextoAno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButtonAddPremiacao, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonRemovePremiacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTextoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemovePremiacao)
                    .addComponent(jButtonAddPremiacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Premiações", jPanel4);

        jLabel24.setText("Evento");

        jLabel25.setText("Pontos");

        jComboBoxProva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhuma" }));

        jLabel26.setText("Prova");

        jScrollPane6.setViewportView(jListSequencias);

        jButtonAddSequencia.setText("+");
        jButtonAddSequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSequenciaActionPerformed(evt);
            }
        });

        jButtonRemoveSequencia.setText("-");
        jButtonRemoveSequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveSequenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextoEvento, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jTextoPontos))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxProva, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonAddSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoveSequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBoxProva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddSequencia)
                        .addComponent(jButtonRemoveSequencia))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel25)
                        .addComponent(jTextoPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Melhores Sequencias", jPanel5);

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jComboBoxPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Prova" }));

        jTextoPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoPesquisaActionPerformed(evt);
            }
        });
        jTextoPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextoPesquisaKeyReleased(evt);
            }
        });

        jButtonPesquisa.setText("Pesquisa");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPainel2Layout = new javax.swing.GroupLayout(jPainel2);
        jPainel2.setLayout(jPainel2Layout);
        jPainel2Layout.setHorizontalGroup(
            jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(jPainel2Layout.createSequentialGroup()
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPainel2Layout.createSequentialGroup()
                                .addComponent(jComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPainel2Layout.createSequentialGroup()
                                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(jTextoDataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(jTextoAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))))
                            .addGroup(jPainel2Layout.createSequentialGroup()
                                .addComponent(jButtonAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))))
                        .addGap(37, 37, 37)))
                .addContainerGap())
        );
        jPainel2Layout.setVerticalGroup(
            jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPainel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisa)))
                    .addGroup(jPainel2Layout.createSequentialGroup()
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextoDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPainel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdicionar)
                            .addComponent(jButtonEditar)
                            .addComponent(jButtonSalvar)
                            .addComponent(jButtonLimpar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPainelTab1.addTab("Listar", jPainel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPainelTab1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPainelTab1)
                .addContainerGap())
        );

        jPainelTab1.getAccessibleContext().setAccessibleName("Adicionar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
    this.clearFields();
}//GEN-LAST:event_jButtonLimparActionPerformed

private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
    this.setEditable(true);
    this.saveMode = 0;
}//GEN-LAST:event_jButtonEditarActionPerformed

private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
    this.clearFields();
    this.setEditable(true);
    this.saveMode = 1;
}//GEN-LAST:event_jButtonAdicionarActionPerformed

private void jButtonAddTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTelefoneActionPerformed
    if (this.validateAddTelefones()) {
        jModelTelefones.addElement(jTextoTelefone.getText());
    }

}//GEN-LAST:event_jButtonAddTelefoneActionPerformed

private void jButtonRemoveTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveTelefoneActionPerformed
    if (jListTelefones.getSelectedIndex() != -1) {
        jModelTelefones.remove(jListTelefones.getSelectedIndex());
    }

}//GEN-LAST:event_jButtonRemoveTelefoneActionPerformed

private void jButtonAddProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddProvaActionPerformed
    if (this.validateAddProvas()) {
        Prova p = new Prova(Integer.parseInt(jTextoDistancia.getText()), jTextoArma.getText(), jTextoModo.getText());
        jModelProvas.addElement(p);
        this.reloadComboProva();
    }

}//GEN-LAST:event_jButtonAddProvaActionPerformed

private void jButtonRemoveProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveProvaActionPerformed
    if (jListProvas.getSelectedIndex() != -1) {
        jModelProvas.remove(jListProvas.getSelectedIndex());
        this.reloadComboProva();
    }
}//GEN-LAST:event_jButtonRemoveProvaActionPerformed

private void jButtonAddPremiacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPremiacaoActionPerformed
    if (this.validateAddPremiacoes()) {
        Premiacao p = new Premiacao(jTextoTitulo.getText(), Integer.parseInt(jTextoAno.getText()));
        jModelPremiacao.addElement(p);
    }

}//GEN-LAST:event_jButtonAddPremiacaoActionPerformed

private void jButtonRemovePremiacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePremiacaoActionPerformed
    if (jListPremiacao.getSelectedIndex() != -1) {
        jModelPremiacao.remove(jListPremiacao.getSelectedIndex());
    }

}//GEN-LAST:event_jButtonRemovePremiacaoActionPerformed

private void jButtonAddSequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSequenciaActionPerformed
    if (this.validateAddMelhoresSequencias()) {
        Sequencia s = new Sequencia((Prova) jComboBoxProva.getSelectedItem(), jTextoEvento.getText(), Integer.parseInt(jTextoPontos.getText()));
        jModelSequencias.addElement(s);
    }

}//GEN-LAST:event_jButtonAddSequenciaActionPerformed

private void jButtonRemoveSequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveSequenciaActionPerformed
    if (jListSequencias.getSelectedIndex() != -1) {
        jModelSequencias.remove(jListSequencias.getSelectedIndex());
    }
}//GEN-LAST:event_jButtonRemoveSequenciaActionPerformed

private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
    if (validateFields()) {
        char sexo;
        char classe;
        char posicao;
        if (jComboBoxClasse.getSelectedIndex() == 0) {
            classe = 'N';
        } else {
            classe = 'P';
        }
        if (jComboBoxSexo.getSelectedIndex() == 0) {
            sexo = 'M';
        } else {
            sexo = 'F';
        }
        if (jComboBoxPosicao.getSelectedIndex() == 0) {
            posicao = 'D';
        } else {
            posicao = 'C';
        }

        Atirador atirador = new Atirador(jTextoNome.getText());
        ArrayList<Prova> provas = new ArrayList<Prova>();
        ArrayList<Sequencia> sequencias = new ArrayList<Sequencia>();
        ArrayList<Premiacao> premiacoes = new ArrayList<Premiacao>();
        Endereco endereco = new Endereco();
        ArrayList<String> telefones = new ArrayList<String>();

        for (int i = 0; i < jModelProvas.size(); i++) {
            provas.add((Prova) jModelProvas.get(i));
        }
        for (int i = 0; i < jModelSequencias.size(); i++) {
            sequencias.add((Sequencia) jModelSequencias.get(i));
        }
        for (int i = 0; i < jModelPremiacao.size(); i++) {
            premiacoes.add((Premiacao) jModelPremiacao.get(i));
        }
        for (int i = 0; i < jModelTelefones.size(); i++) {
            telefones.add((String) jModelTelefones.get(i));
        }

        endereco.setBairro(jTextoBairro.getText());
        endereco.setCep(jTextoCep.getText());
        endereco.setCidade(jTextoCidade.getText());
        endereco.setComplemento(jTextoComplemento.getText());
        endereco.setEstado(jTextoEstado.getText());
        endereco.setLogradouro(jTextoLogradouro.getText());
        endereco.setNumero(jTextoNumero.getText());
        endereco.setPais(jTextoPais.getText());



        atirador.setAltura(Double.parseDouble(jTextoAltura.getText()));
        atirador.setPeso(Double.parseDouble(jTextoPeso.getText()));
        atirador.setClasse(classe);
        atirador.setSexo(sexo);
        atirador.setPosicao(posicao);
        atirador.setCpf(jTextoCpf.getText());
        try {
            atirador.setDataNascimento(dateFormat.parse(jTextoDataNasc.getText()));
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar a data informada!");
            atirador.setDataNascimento(null);
        }
        atirador.setEndereco(endereco);
        atirador.setMelhoresSequencias(sequencias);
        atirador.setNome(jTextoNome.getText());
        atirador.setNomeMae(jTextoNomeMae.getText());
        atirador.setNomePai(jTextoNomePai.getText());
        atirador.setPremiacoes(premiacoes);
        atirador.setProvas(provas);
        atirador.setRg(jTextoRg.getText());
        atirador.setTelefones(telefones);

        try {
            if (saveMode == 0) {
                if (atiradorSelecionado != null) {
                    Atirador aux = atiradorSelecionado;
                    controle.removeAtirador(controle.getAtirador(aux.getNome()));
                    controle.addAtirador(atirador);
                }
            } else if (saveMode == 1) {
                controle.addAtirador(atirador);
            }
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar os dados informados!");
        }
    }
    this.reloadMainList();
}//GEN-LAST:event_jButtonSalvarActionPerformed

private void jListAtiradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAtiradoresMouseClicked
    this.fillFields();
}//GEN-LAST:event_jListAtiradoresMouseClicked

private void jTextoPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoPesquisaActionPerformed
}//GEN-LAST:event_jTextoPesquisaActionPerformed

private void jTextoPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextoPesquisaKeyReleased
    this.dinamicSearch();
}//GEN-LAST:event_jTextoPesquisaKeyReleased

private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
    if (JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?") == 0) {
        controle.removeAtirador(atiradorSelecionado);
        this.clearFields();
        this.reloadMainList();
    }
}//GEN-LAST:event_jButtonExcluirActionPerformed

private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
    this.dinamicSearch();

}//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jListAtiradoresActionPerformed(ListSelectionEvent evt) {
        //this.fillFields();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAtirador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAtirador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAtirador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAtirador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastroAtirador().setVisible(true);
            }
        });



    }

    public Object getSelected(JList list) {
        if (list.getSelectedIndex() != -1) {
            return list.getModel().getElementAt(list.getSelectedIndex());
        } else {
            return null;
        }
    }

    public void setList(JList list, ArrayList<Atirador> itens) {
        CustomListCellRenderer renderer = new CustomListCellRenderer();
        list.setCellRenderer(renderer);
        DefaultListModel lista = new DefaultListModel();
        for (Atirador a : itens) {
            lista.addElement(a);
        }
        list.setModel(lista);
    }

    public void fillFields() {

        if (jListAtiradores.getSelectedIndex() != -1) {
            Atirador atirador = (Atirador) getSelected(jListAtiradores);
            this.clearFields();
            if (atirador.getProvas() != null) {
                for (Prova p : atirador.getProvas()) {
                    jModelProvas.addElement(p);
                    jComboBoxProva.addItem(p);
                }
                for (Prova p : atirador.getProvas()) {
                    
                }
            }
            if (atirador.getPremiacoes() != null) {
                for (Premiacao p : atirador.getPremiacoes()) {
                    jModelPremiacao.addElement(p);
                }
            }
            if (atirador.getTelefones() != null) {
                for (String s : atirador.getTelefones()) {
                    jModelTelefones.addElement(s);
                }
            }
            if (atirador.getMelhoresSequencias() != null) {
                for (Sequencia s : atirador.getMelhoresSequencias()) {
                    jModelSequencias.addElement(s);
                }

            }

            if (atirador.getDataNascimento() == null) {
                jTextoDataNasc.setText("");
            } else {
                jTextoDataNasc.setText(dateFormat.format(atirador.getDataNascimento()));
            }

            jTextoNome.setText(atirador.getNome());
            jTextoAltura.setText(String.valueOf(atirador.getAltura()));
            jTextoCpf.setText(atirador.getCpf());
            jTextoDataNasc.setText(dateFormat.format(atirador.getDataNascimento()));
            jTextoNomeMae.setText(atirador.getNomeMae());
            jTextoNomePai.setText(atirador.getNomePai());
            jTextoRg.setText(atirador.getRg());
            jTextoPeso.setText(String.valueOf(atirador.getPeso()));
            jTextoLogradouro.setText(atirador.getEndereco().getLogradouro());
            jTextoComplemento.setText(atirador.getEndereco().getComplemento());
            jTextoCidade.setText(atirador.getEndereco().getCidade());
            jTextoPais.setText(atirador.getEndereco().getPais());
            jTextoBairro.setText(atirador.getEndereco().getBairro());
            jTextoCep.setText(atirador.getEndereco().getCep());
            jTextoEstado.setText(atirador.getEndereco().getEstado());
            jTextoNumero.setText(atirador.getEndereco().getNumero());
            jTextoAno.setText("");
            jTextoArma.setText("");
            jTextoDistancia.setText("");
            jTextoEvento.setText("");
            jTextoModo.setText("");
            jTextoTelefone.setText("");
            jTextoTitulo.setText("");
            switch (atirador.getSexo()) {
                case 'M':
                    jComboBoxSexo.setSelectedIndex(0);
                    break;
                case 'F':
                    jComboBoxSexo.setSelectedIndex(1);
                    break;

            }
            switch (atirador.getClasse()) {
                case 'N':
                    jComboBoxClasse.setSelectedIndex(0);
                    break;
                case 'P':
                    jComboBoxClasse.setSelectedIndex(1);
                    break;
            }
            switch (atirador.getPosicao()) {
                case 'D':
                    jComboBoxPosicao.setSelectedIndex(0);
                    break;
                case 'C':
                    jComboBoxPosicao.setSelectedIndex(1);
                    break;

            }
            this.atiradorSelecionado = atirador;
            this.saveMode = 0;
        }

    }

    public void dinamicSearch() {
        ArrayList<Atirador> atiradores = new ArrayList<Atirador>();
        if (jComboBoxPesquisa.getSelectedIndex() == 0) {
            try {
                atiradores = controle.listaAtirador(jTextoPesquisa.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar a Lista!");
            }
        } else {
            try {
                atiradores = controle.listaAtirador(controle.getProvas(jTextoPesquisa.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao buscar a Lista!");
            }

        }
        reloadMainList(atiradores);
    }

    public void setEditable(boolean op) {
        jTextoNome.setEditable(op);
        jTextoAltura.setEditable(op);
        jTextoCpf.setEditable(op);
        jTextoDataNasc.setEditable(op);
        jTextoNomeMae.setEditable(op);
        jTextoNomePai.setEditable(op);
        jTextoRg.setEditable(op);
        jTextoPeso.setEditable(op);
        jTextoLogradouro.setEditable(op);
        jTextoComplemento.setEditable(op);
        jTextoCidade.setEditable(op);
        jTextoPais.setEditable(op);
        jTextoBairro.setEditable(op);
        jTextoCep.setEditable(op);
        jTextoEstado.setEditable(op);
        jTextoNumero.setEditable(op);
        jTextoAno.setEditable(op);
        jTextoArma.setEditable(op);
        jTextoDistancia.setEditable(op);
        jTextoEvento.setEditable(op);
        jTextoModo.setEditable(op);
        jTextoTelefone.setEditable(op);
        jTextoTitulo.setEditable(op);
        jTextoPontos.setEditable(op);
    }

    public void reloadMainList() {
        jModelAtiradores.clear();
        for (Atirador at : controle.listaAtirador()) {
            jModelAtiradores.addElement(at);
            jListAtiradores.setModel(jModelAtiradores);
        }
    }

    public void reloadMainList(ArrayList<Atirador> list) {
        jModelAtiradores.clear();
        for (Atirador at : list) {
            jModelAtiradores.addElement(at);
            jListAtiradores.setModel(jModelAtiradores);
        }
    }

    private void initMoreComponents() {
        this.setEditable(false);
        this.dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        CustomListCellRenderer renderer = new CustomListCellRenderer();
        emptyModel = new DefaultComboBoxModel();
        jListAtiradores.setCellRenderer(renderer);
        this.atiradorSelecionado = null;
        this.jModelTelefones = new DefaultListModel();
        this.jListTelefones.setModel(jModelTelefones);
        this.jModelDefault = new DefaultListModel();
        this.jModelAtiradores = new DefaultListModel();
        this.jListAtiradores.setModel(jModelAtiradores);
        this.jModelProvas = new DefaultListModel();
        this.jListProvas.setModel(jModelProvas);
        this.jModelPremiacao = new DefaultListModel();
        this.jListPremiacao.setModel(jModelPremiacao);
        this.jModelSequencias = new DefaultListModel();
        this.jListSequencias.setModel(jModelSequencias);
        controle = new ControleAtirador();
        this.preparedEntry();
        this.reloadMainList();
        jListAtiradores.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                jListAtiradoresActionPerformed(e);
            }
        });
    }

    public void preparedEntry() {
        Atirador atirador = new Atirador(jTextoNome.getText());
        ArrayList<Prova> provas = new ArrayList<Prova>();
        ArrayList<Sequencia> sequencias = new ArrayList<Sequencia>();
        ArrayList<Premiacao> premiacoes = new ArrayList<Premiacao>();
        Endereco endereco = new Endereco();
        ArrayList<String> telefones = new ArrayList<String>();

        Prova p = new Prova();
        p.setArma("Shotgun");
        p.setDistancia(20);
        p.setModo("Prone");
        provas.add(p);
        Sequencia s = new Sequencia(p, "Olimpíadas de Athenas - 2006", 1350);
        sequencias.add(s);
        Premiacao pm = new Premiacao("Campeão Olímpico", 2006);
        premiacoes.add(pm);

        endereco.setBairro("Gama");
        endereco.setCep("72000-000");
        endereco.setCidade("Brasília");
        endereco.setComplemento("");
        endereco.setEstado("DF");
        endereco.setLogradouro("Qr. 32 Conj. F");
        endereco.setNumero("3");
        endereco.setPais("Brasil");

        telefones.add("61 3333-4444");
        telefones.add("61 3555-4444");

        atirador.setAltura(1.80);
        atirador.setPeso(70.0);
        atirador.setClasse('N');
        atirador.setSexo('M');
        atirador.setPosicao('D');
        atirador.setCpf("111.111.111-11");
        try {
            atirador.setDataNascimento(dateFormat.parse("12/12/2012"));
        } catch (ParseException e) {
            atirador.setDataNascimento(null);
        }
        atirador.setEndereco(endereco);
        atirador.setMelhoresSequencias(sequencias);
        atirador.setNome("André");
        atirador.setNomeMae("");
        atirador.setNomePai("");
        atirador.setPremiacoes(premiacoes);
        atirador.setProvas(provas);
        atirador.setRg("333.333-3");
        atirador.setTelefones(telefones);

        controle.addAtirador(atirador);
    }

    public void reloadComboProva() {
        jComboBoxProva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhuma" }));
        ArrayList<Prova> pList = new ArrayList();
        for (int i = 0; i < jModelProvas.size(); i++) {
            pList.add((Prova) jModelProvas.get(i));
        }
        for (Prova p : pList) {
            jComboBoxProva.addItem(p);
        }
    }

    public void clearFields() {
        jTextoNome.setText("");
        jTextoAltura.setText("0.0");
        jTextoCpf.setText("");
        jTextoDataNasc.setText("");
        jTextoNomeMae.setText("");
        jTextoNomePai.setText("");
        jTextoRg.setText("");
        jTextoPeso.setText("0.0");
        jTextoLogradouro.setText("");
        jTextoComplemento.setText("");
        jTextoCidade.setText("");
        jTextoPais.setText("");
        jTextoBairro.setText("");
        jTextoCep.setText("");
        jTextoEstado.setText("");
        jTextoNumero.setText("");
        jComboBoxProva.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nenhuma" }));
        jComboBoxSexo.setSelectedIndex(0);
        jComboBoxProva.setSelectedIndex(0);
        jComboBoxClasse.setSelectedIndex(0);
        jComboBoxPosicao.setSelectedIndex(0);
        jTextoAno.setText("");
        jTextoArma.setText("");
        jTextoDistancia.setText("");
        jTextoEvento.setText("");
        jTextoModo.setText("");
        jTextoTelefone.setText("");
        jTextoTitulo.setText("");
        jModelPremiacao.clear();
        jModelSequencias.clear();
        jModelTelefones.clear();
        jModelProvas.clear();
        jTextoPontos.setText("0");

    }

    public boolean validateFields() {
        if (jTextoNome.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(null, "O campo Nome deve ser maior que 3 caracteres!");
            return false;
        }
        if (jTextoRg.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Rg não pode ser vazio!");
            return false;
        }
        if (jTextoCpf.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(null, "O campo CPF não pode ser vazio!");
            return false;
        }
        if (jTextoAltura.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Altura não pode ser vazio!");
            return false;
        } else {
            try {
                Double.parseDouble(jTextoAltura.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo Ano deve ser real!");
                return false;
            }
        }
        if (jTextoPeso.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Peso não pode ser vazio!");
            return false;
        } else {
            try {
                Double.parseDouble(jTextoPeso.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo Peso deve ser real!");
                return false;
            }
        }
        if (jTextoDataNasc.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Data Nasc. não pode ser vazio!");
            return false;
        } else {
            try {
                dateFormat.parse(jTextoDataNasc.getText());
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "A data informada é invalida!");
                return false;
            }
        }
        return true;
    }

    public boolean validateAddTelefones() {
        if (jTextoTelefone.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Telefone não pode ser vazio!");
            return false;
        }
        return true;
    }

    public boolean validateAddProvas() {
        if (jTextoDistancia.getText().trim().length() <= 0) {

            JOptionPane.showMessageDialog(null, "O campo Distancia não pode ser vazio!");
            return false;
        } else {
            try {
                Integer.parseInt(jTextoDistancia.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo Distancia deve ser inteiro, em metros!");
                return false;
            }

        }
        if (jTextoArma.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Arma não pode ser vazio!");
            return false;
        }
        if (jTextoModo.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Modo não pode ser vazio!");
            return false;
        }

        return true;
    }

    public boolean validateAddPremiacoes() {
        if (jTextoTitulo.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Titulo não pode ser vazio!");
            return false;
        }
        if (jTextoAno.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Ano não pode ser vazio!");
            return false;
        } else {
            try {
                Integer.parseInt(jTextoAno.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo Ano deve ser inteiro!");
                return false;
            }
        }
        return true;
    }

    public boolean validateAddMelhoresSequencias() {
        if (jTextoEvento.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Evento não pode ser vazio!");
            return false;
        }
        if (jTextoPontos.getText().trim().length() <= 0) {
            JOptionPane.showMessageDialog(null, "O campo Pontos não pode ser vazio!");
            return false;
        } else {
            try {
                Integer.parseInt(jTextoPontos.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "O campo Pontos deve ser inteiro!");
                return false;
            }
        }
        try {
            if (jComboBoxProva.getSelectedItem() != null) {
                jModelProvas.contains((Prova) jComboBoxProva.getSelectedItem());
            } else {
                JOptionPane.showMessageDialog(null, "A prova selecionada não está contida na lista de provas!");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "A prova selecionada não está contida na lista de provas!");
            return false;
        }
        return true;
    }

    public void reloadLists() {
        jListProvas.setModel(jModelProvas);
        jListPremiacao.setModel(jModelPremiacao);
        jListSequencias.setModel(jModelSequencias);
        jListAtiradores.setModel(jModelAtiradores);
        jListTelefones.setModel(jModelTelefones);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPremiacao;
    private javax.swing.JButton jButtonAddProva;
    private javax.swing.JButton jButtonAddSequencia;
    private javax.swing.JButton jButtonAddTelefone;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonRemovePremiacao;
    private javax.swing.JButton jButtonRemoveProva;
    private javax.swing.JButton jButtonRemoveSequencia;
    private javax.swing.JButton jButtonRemoveTelefone;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxClasse;
    private javax.swing.JComboBox jComboBoxPesquisa;
    private javax.swing.JComboBox jComboBoxPosicao;
    private javax.swing.JComboBox jComboBoxProva;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListAtiradores;
    private javax.swing.JList jListPremiacao;
    private javax.swing.JList jListProvas;
    private javax.swing.JList jListSequencias;
    private javax.swing.JList jListTelefones;
    private javax.swing.JPanel jPainel2;
    private javax.swing.JTabbedPane jPainelTab1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextoAltura;
    private javax.swing.JTextField jTextoAno;
    private javax.swing.JTextField jTextoArma;
    private javax.swing.JTextField jTextoBairro;
    private javax.swing.JTextField jTextoCep;
    private javax.swing.JTextField jTextoCidade;
    private javax.swing.JTextField jTextoComplemento;
    private javax.swing.JTextField jTextoCpf;
    private javax.swing.JTextField jTextoDataNasc;
    private javax.swing.JTextField jTextoDistancia;
    private javax.swing.JTextField jTextoEstado;
    private javax.swing.JTextField jTextoEvento;
    private javax.swing.JTextField jTextoLogradouro;
    private javax.swing.JTextField jTextoModo;
    private javax.swing.JTextField jTextoNome;
    private javax.swing.JTextField jTextoNomeMae;
    private javax.swing.JTextField jTextoNomePai;
    private javax.swing.JTextField jTextoNumero;
    private javax.swing.JTextField jTextoPais;
    private javax.swing.JTextField jTextoPeso;
    private javax.swing.JTextField jTextoPesquisa;
    private javax.swing.JTextField jTextoPontos;
    private javax.swing.JTextField jTextoRg;
    private javax.swing.JTextField jTextoTelefone;
    private javax.swing.JTextField jTextoTitulo;
    // End of variables declaration//GEN-END:variables
}
